name: data-pipeline-workflow

on:
  push: 
  workflow_dispatch:
  schedule:
        - cron: "35 0 * * *"

jobs: 
    run-data-pipeline:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repo content
              uses: actions/checkout@v4
              with: 
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN}} #push code to the Repo will require access
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python_version: "3.9"
                cache: "pip"
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run data pipeline
              env: 
                YT_API_KEY: ${{ secrets.YT_API_KEY}}
              run: python data_pipeline.py
            - name: Check for changes # create env variable indicating if any changes were made, store in GITHUB_ENV
              id: git-check
              run: |
                git config user.name 'github-actions'
                git config user.email 'github-actions@github.com'
                git add .
                git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV 
            - name: Commit and push if changes # if changes made push new data to repo
              if: env.changes == 'true' 
              run: |
                git commit -m "updated video index"
                git push
    


